[package]
name = "rgb-lib"
version = "0.1.0-alpha.1"
authors = ["Zoe Faltibà <zoefaltiba@gmail.com>", "Nicola Busanello <nicola.busanello@gmail.com>"]
edition = "2021"
rust-version = "1.59.0"
repository = "https://github.com/RGB-Tools/rgb-lib"
homepage = "https://github.com/RGB-Tools/rgb-lib"
license = "MIT"
description = "RGB wallet library"
exclude = ["migration"]

[workspace]
members = [".", "migration"]

[dependencies]
base64 = "0.13.0"
bdk = { version = "0.21", features = ["electrum", "keys-bip39", "sqlite-bundled"] }
bitcoin = "0.28.1"
electrum-client = "0.10.2"
futures = "0.3"
rgb_lib_migration = { path = "migration", version = "0.1.0" }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "multipart"] }
sea-orm = { version = "^0.8.0", features = ["sqlx-mysql", "sqlx-postgres", "sqlx-sqlite", "runtime-async-std-native-tls", "macros"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"
thiserror = "1.0"
time = { version = "0.3.13", features = ["std"] }

# RGB-related deps
amplify = "=3.13.0"
amplify_num = "=0.4.1"
bp-core = { version = "=0.8.0", features = ["psbt", "wallet"] }
bp-dbc = "=0.8.0"
internet2 = "=0.8.3"
lnpbp = "=0.8.0"
psbt = "=0.8.5"
rgb-std = { git = "https://github.com/zoedberg/rgb-std", branch = "fix/rgb_core", version = "0.8.0" }
rgb20 = { git = "https://github.com/zoedberg/rust-rgb20", branch = "fix/rgb_core", version = "0.8.0-rc.4" }
rgb_core = { package = "rgb-core", git = "https://github.com/RGB-WG/rgb-core", branch = "master", version = "0.8.0" }
rgb_node = { git = "https://github.com/zoedberg/rgb-node", branch = "fix/various2", version = "0.8.0-rc.1", features = ["server", "embedded"] }
rgb_rpc = { git = "https://github.com/zoedberg/rgb-node", branch = "fix/various2", version = "0.8.0-rc.1" }
stens = "=0.7.1"
store_daemon = "=0.8.0"
strict_encoding = "=0.8.1"

[dev-dependencies]
tempdir = "0.3"
