[package]
name = "rgb-lib"
version = "0.1.0-alpha.1"
authors = ["Zoe Faltibà <zoefaltiba@gmail.com>", "Nicola Busanello <nicola.busanello@gmail.com>"]
edition = "2021"
rust-version = "1.59.0"
repository = "https://github.com/RGB-Tools/rgb-lib"
homepage = "https://github.com/RGB-Tools/rgb-lib"
license = "MIT"
description = "RGB wallet library"

[workspace]
members = ["."]

[dependencies]
bdk = { version = "0.21", features = ["electrum", "keys-bip39", "sqlite-bundled"] }
bitcoin = "0.28.1"
thiserror = "1.0"
