[package]
name = "rgb-lib"
version = "0.1.9"
authors = ["Zoe Faltibà <zoefaltiba@gmail.com>", "Nicola Busanello <nicola.busanello@gmail.com>"]
edition = "2021"
rust-version = "1.59.0"
repository = "https://github.com/RGB-Tools/rgb-lib"
homepage = "https://github.com/RGB-Tools/rgb-lib"
license = "MIT"
description = "RGB wallet library"
exclude = ["migration"]

[workspace]
members = [".", "migration"]

[dependencies]
base64 = "0.21.0"
bdk = { version = "0.27", features = ["electrum", "keys-bip39", "sqlite-bundled"] }
bitcoin = "0.29.2"
chrono = "0.4.24"
electrum-client = "0.12.0"
futures = "0.3"
rgb-lib-migration = { path = "migration", version = "0.1.8" }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "multipart", "native-tls"] }
sea-orm = { version = "^0.11.3", features = ["sqlx-mysql", "sqlx-postgres", "sqlx-sqlite", "runtime-async-std-native-tls", "macros"] }
sea-query = "=0.28.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"
thiserror = "1.0"
time = { version = "0.3.20", features = ["std"] }
tree_magic = "0.2.3"

# RGB-related deps
amplify = "=3.13.0"
amplify_num = "=0.4.1"
bp-core = { version = "=0.9.0", features = ["psbt", "wallet"] }
bp-dbc = "=0.9.0"
commit_verify = "=0.9.0"
internet2 = "=0.9.0"
lnpbp = "=0.9.0"
lnpbp-invoice = { version = "0.9.0", features = ["rgb"] }
psbt = "=0.9.0"
rgb-std = "=0.9.0"
rgb20 = "=0.9.0"
rgb121 = "0.2.0"
rgb_core = { package = "rgb-core", version = "=0.9.0" }
rgb_node = { version = "=0.9.2", features = ["server", "embedded"] }
rgb_rpc = { version = "=0.9.1" }
stens = "=0.9.0"
store_daemon = "=0.9.0"
strict_encoding = "=0.9.0"

[dev-dependencies]
once_cell = "1.17.1"
tempfile = "3.5"
