[package]
name = "rgb-lib-ffi-bindgen"
version = "0.1.0"
authors = ["Zoe Faltibà <zoefaltiba@gmail.com>", "Nicola Busanello <nicola.busanello@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
camino = "1.1"
structopt = "0.3"
uniffi_bindgen = "0.22.0"
